name: simpy
channels:
  - defaults
dependencies:
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytest
  - python=3.10
  - scipy
  - pip:
    - simpy==4.0
    - stroke-outcome

